language: node_js
node_js:
  - stable
  - "4"
branches:
  only:
    - master
sudo: false
before_script:
  - npm run fetch-test-data
  - npm run generate-test-data
script:
  - npm run test
  - npm run test-interop
