language: node_js
sudo: false
node_js:
  - stable
  - "6"
  - "4"
branches:
  only:
    - master
before_script:
  - npm run test:fetch
  - npm run test:generate
script:
  - npm run test
  - npm run test:interop
